<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JobCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        Category::insert([
            ['name' => 'software development'],
            ['name' => 'design'],
            ['name' => 'marketing'],
            ['name' => 'sales'],
            ['name' => 'customer support'],
            ['name' => 'business & management'],
            ['name' => 'product management'],
            ['name' => 'data analysis'],
            ['name' => 'devops'],
            ['name' => 'quality assurance'],
            ['name' => 'project management'],
            ['name' => 'human resources'],
            ['name' => 'accounting'],
            ['name' => 'finance'],
            ['name' => 'legal'],
            ['name' => 'operations'],
            ['name' => 'content writing'],
            ['name' => 'social media'],
            ['name' => 'seo'],
            ['name' => 'graphic design'],
            ['name' => 'ux/ui design'],
            ['name' => 'video production'],
            ['name' => 'photography'],
            ['name' => 'web development'],
            ['name' => 'mobile development'],
            ['name' => 'game development'],
            ['name' => 'machine learning'],
            ['name' => 'artificial intelligence'],
            ['name' => 'cloud architecture'],
            ['name' => 'database administration'],
            ['name' => 'system administration'],
            ['name' => 'network engineering'],
            ['name' => 'security'],
            ['name' => 'cybersecurity'],
            ['name' => 'business analysis'],
            ['name' => 'technical writing'],
            ['name' => 'copywriting'],
            ['name' => 'brand strategy'],
            ['name' => 'event management'],
            ['name' => 'customer success'],
            ['name' => 'sales engineering'],
            ['name' => 'business development'],
            ['name' => 'recruitment'],
            ['name' => 'training & development'],
            ['name' => 'compliance'],
            ['name' => 'supply chain'],
            ['name' => 'logistics'],
            ['name' => 'procurement'],
            ['name' => 'inventory management'],
            ['name' => 'retail management'],
            ['name' => 'hospitality'],
            ['name' => 'tourism'],
            ['name' => 'education'],
            ['name' => 'healthcare'],
            ['name' => 'nursing'],
            ['name' => 'medical administration'],
            ['name' => 'architecture'],
            ['name' => 'civil engineering'],
            ['name' => 'mechanical engineering'],
            ['name' => 'electrical engineering'],
            ['name' => 'construction'],
            ['name' => 'real estate'],
            ['name' => 'property management'],
            ['name' => 'agriculture'],
            ['name' => 'environmental'],
            ['name' => 'energy'],
            ['name' => 'utilities'],
            ['name' => 'manufacturing'],
            ['name' => 'automotive'],
            ['name' => 'aerospace'],
            ['name' => 'telecommunications'],
            ['name' => 'broadcasting'],
            ['name' => 'journalism'],
            ['name' => 'public relations'],
            ['name' => 'advertising'],
            ['name' => 'market research'],
            ['name' => 'consumer insights'],
            ['name' => 'product design'],
            ['name' => 'industrial design'],
            ['name' => 'fashion design'],
            ['name' => 'interior design'],
            ['name' => 'animation'],
            ['name' => 'illustration'],
            ['name' => 'music production'],
            ['name' => 'sound design'],
            ['name' => 'comedy & entertainment'],
            ['name' => 'sports management'],
            ['name' => 'fitness & wellness'],
            ['name' => 'nutrition'],
            ['name' => 'psychology'],
            ['name' => 'consulting'],
            ['name' => 'law enforcement'],
            ['name' => 'military'],
            ['name' => 'government'],
        ]);
    }
}
