<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class JobTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Tag::insert([
            ['name' => 'remote'],
            ['name' => 'full time'],
            ['name' => 'part time'],
            ['name' => 'contract'],
            ['name' => 'freelance'],
            ['name' => 'senior'],
            ['name' => 'junior'],
            ['name' => 'mid level'],
            ['name' => 'php'],
            ['name' => 'laravel'],
            ['name' => 'vue.js'],
            ['name' => 'react'],
            ['name' => 'mysql'],
            ['name' => 'backend'],
            ['name' => 'frontend'],
            ['name' => 'devops'],
            ['name' => 'ux'],
            ['name' => 'ui'],
            ['name' => 'qa'],
            ['name' => 'mobile'],
            ['name' => 'data science'],
            ['name' => 'machine learning'],
            ['name' => 'python'],
            ['name' => 'javascript'],
            ['name' => 'typescript'],
            ['name' => 'node.js'],
            ['name' => 'aws'],
            ['name' => 'docker'],
            ['name' => 'kubernetes'],
            ['name' => 'sql'],
            ['name' => 'nosql'],
            ['name' => 'postgresql'],
            ['name' => 'graphql'],
            ['name' => 'rest'],
            ['name' => 'api'],
            ['name' => 'agile'],
            ['name' => 'scrum'],
            ['name' => 'kanban'],
            ['name' => 'design'],
            ['name' => 'software engineer'],
            ['name' => 'architect'],
            ['name' => 'product manager'],
            ['name' => 'project manager'],
            ['name' => 'it support'],
            ['name' => 'security'],
            ['name' => 'cloud'],
            ['name' => 'remote friendly'],
            ['name' => 'hybrid'],
            ['name' => 'onsite'],
            ['name' => 'ecommerce'],
            ['name' => 'startup'],
            ['name' => 'enterprise'],
            ['name' => 'contract-to-hire'],
            ['name' => 'internship'],
            ['name' => 'entry level'],
            ['name' => 'lead'],
            ['name' => 'team lead'],
            ['name' => 'full stack'],
            ['name' => '.net'],
            ['name' => 'c#'],
            ['name' => 'java'],
            ['name' => 'go'],
            ['name' => 'ruby'],
            ['name' => 'django'],
            ['name' => 'flask'],
            ['name' => 'angular'],
            ['name' => 'svelte'],
            ['name' => 'swift'],
            ['name' => 'kotlin'],
            ['name' => 'android'],
            ['name' => 'ios'],
            ['name' => 'blockchain'],
            ['name' => 'ai'],
            ['name' => 'nlp'],
            ['name' => 'data analytics'],
            ['name' => 'business intelligence'],
            ['name' => 'salesforce'],
            ['name' => 'sap'],
            ['name' => 'marketing'],
            ['name' => 'content'],
            ['name' => 'social media'],
            ['name' => 'sales'],
            ['name' => 'customer support'],
            ['name' => 'technical writer'],
            ['name' => 'qa automation'],
            ['name' => 'manual testing'],
            ['name' => 'networking'],
            ['name' => 'cybersecurity'],
            ['name' => 'performance'],
            ['name' => 'troubleshooting'],
            ['name' => 'strategy'],
            ['name' => 'leadership'],
            ['name' => 'mentorship'],
            ['name' => 'collaboration'],
            ['name' => 'communication'],
            ['name' => 'time management'],
            ['name' => 'problem solving'],
            ['name' => 'research'],
            ['name' => 'innovation'],
            ['name' => 'compliance'],
        ]);
    }
}
